name: Release
on:
  release:
    types:
      - published

jobs:
  release-notes:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4
        with:
          fetch-depth: 0
          submodules: recursive

      - name: Generate Release Notes
        id: release-notes
        uses: mariomac/linked-release-notes@v0.0.5
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          tag: ${{ github.event.release.tag_name }}

      - name: Update Release with Notes
        run: |
          echo "Submodule has changes!"
          echo "${{ steps.release-notes.outputs.release-notes }}"